version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    groups:
      npm-patch-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      npm-major:
        patterns:
          - "*"
        update-types:
          - "major"
    ignore:
      - dependency-name: "diff"
      - dependency-name: "nanoid"
      - dependency-name: "undici"
      - dependency-name: "form-data"
      - dependency-name: "tar"
      - dependency-name: "qs"
      - dependency-name: "lodash-es"
      - dependency-name: "js-yaml"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "UTC"
    open-pull-requests-limit: 1
    groups:
      actions-patch-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
    commit-message:
      prefix: "ci"
